# Copyright 2025 Chen Xingqiang (YiRage Project)
# SPDX-License-Identifier: Apache-2.0
"""RuntimeFusion serving surface (FusionPlan / FusionCapsule / RF.step).

Product concepts (not Mirage MPK/µGraph):
- FusionPlan: searched/cached local execution plan
- FusionCapsule: engine-schedulable fused block
- RuntimeFusion: per-step select/orchestrate capsules from engine meta

Legacy symbols (``mugraph``, ``PersistentKernel``, …) may back implementations later;
this package is the public RF identity.
"""

from .capsule import FusionCapsule
from .engine_stub import (
    EngineAttentionMeta,
    EngineDecoderLayerStub,
    EngineModelStub,
    QWEN2_MLP_HF_ATTACH,
)
from .hybrid_model import HybridModelOverride, resolve_rf_mlp_layer_ids
from .kv_meta import (
    PagedKvMeta,
    attach_paged_kv_to_step_meta,
    block_tables_to_paged_kv,
    last_page_len_from_seq,
)
from .radix_meta import (
    RadixHitMeta,
    apply_radix_shrink,
    attach_radix_to_step_meta,
    build_sglang_rf_step_meta,
    parse_radix_hit_mask,
    radix_hit_mask_from_sglang_extend_lens,
)
from .sglang_e2e import (
    SglangForwardBatchSpec,
    SglangHybridE2EReport,
    SglangMlpRfE2EReport,
    build_minimal_sglang_qwen2_decoder_layer,
    run_sglang_mlp_rf_e2e_auto,
    run_sglang_qwen2_mlp_rf_e2e,
    run_torch_sglang_hybrid_full_e2e,
    run_torch_sglang_mlp_rf_e2e,
)
from .sglang_plugin import (
    SGLANG_QWEN2_MLP_ATTACH,
    SglangBatchTorchMlpRfHook,
    SglangMlpWeightView,
    SglangQwen2MlpRfHook,
    build_sglang_batch_torch_mlp_rf_hook,
    build_sglang_qwen2_mlp_rf_hook,
    extract_qwen2_mlp_weights as extract_sglang_qwen2_mlp_weights,
    is_sglang_available,
    require_sglang,
    rf_step_meta_from_forward_batch,
)
from .torch_plugin import TorchDecoderMlpRfHook, build_torch_mlp_rf_hook
from .vllm_e2e import (
    VllmHybridE2EReport,
    VllmMlpRfE2EReport,
    build_minimal_vllm_qwen2_decoder_layer,
    run_torch_vllm_hybrid_full_e2e,
    run_torch_vllm_mlp_rf_e2e,
    run_vllm_mlp_rf_e2e_auto,
    run_vllm_qwen2_mlp_rf_e2e,
)
from .hf_qwen_cpu_e2e import (
    DEFAULT_QWEN05B_MODEL,
    HfQwen05bCpuE2EReport,
    HfQwen2MlpLayerAdapter,
    HfQwen2MlpRfHook,
    build_hf_qwen_mlp_rf_hook,
    greedy_decode_with_rf_mlp,
    is_transformers_available,
    qwen2_decode_step_with_rf_mlp,
    qwen2_forward_with_rf_mlp,
    require_transformers,
    resolve_hf_qwen_mlp_backend,
    run_hf_qwen05b_cpu_e2e,
)
from .vllm_paged_e2e import (
    VllmPagedFullLayerE2EReport,
    VllmPagedKvBatchSpec,
    run_torch_vllm_paged_full_layer_e2e,
    run_vllm_paged_full_layer_e2e_auto,
)
from .vllm_plugin import (
    VLLM_QWEN2_MLP_ATTACH,
    VllmMlpWeightView,
    VllmQwen2MlpRfHook,
    build_vllm_qwen2_mlp_rf_hook,
    extract_qwen2_mlp_weights,
    is_vllm_available,
    require_vllm,
    require_vllm_cpu_serving,
)
from .bootstrap import bootstrap_yirage_stub, import_serving, repo_root, require_numpy
from .cpu_cert import (
    CertReport,
    CertStage,
    run_serving_cpu_cert,
    serving_cpu_cert_manifest,
)
from .sm_budget import (
    DEFAULT_CAPSULE_SM_COST,
    DEFAULT_RESERVED_AUX_SMS,
    DEFAULT_TOTAL_SMS,
    SmStepAllocation,
    SmWorkerQuota,
    assert_aux_coresidence,
    capsule_sm_cost,
    resolve_sm_worker_quota,
)
from .exec_backend import (
    BACKEND_YIRAGE_MACA,
    BACKEND_NUMPY_REF,
    BACKEND_TORCH,
    BACKEND_YIRAGE_CPU,
    default_serving_backend,
    is_maca_serving_backend,
    is_exec_backend,
    is_yirage_backend,
)
from .torch_engine import TorchAttentionMeta, TorchDecoderLayer, TorchEngineModel
from .torch_exec import (
    BenchResult,
    bench_forward,
    default_device,
    mlp_torch,
    require_torch,
    to_numpy,
    to_torch,
)
from .capsule_orchestration import (
    build_split_mlp_runtime_fusion,
    pipeline_meta_for_layer,
    resolve_capsule_pipeline,
    split_mlp_down_name,
    split_mlp_gate_up_name,
    split_mlp_pipeline_names,
)
from .layer_override import (
    LayerForwardResult,
    RuntimeFusionMlpLayerOverride,
    build_layer_mlp_capsule,
    capsule_name_for_layer,
)
from .mlp_capsule import MlpFusionCapsule, mlp_eager_numpy
from .plan import FusionPlan
from .segment_override import (
    DecoderSegmentOverride,
    RuntimeFusionSplitMlpLayerOverride,
    SegmentForwardResult,
    SegmentHybridModelOverride,
    resolve_segment_layer_ids,
)
from .split_mlp_capsule import (
    MlpDownFusionCapsule,
    MlpGateUpFusionCapsule,
    build_layer_split_mlp_capsules,
    split_mlp_matches_fused,
    split_mlp_parity_numpy,
)
from .bench_archive import (
    ServingBenchArchive,
    ServingBenchArchiveRow,
    TorchSegmentForwardResult,
    TorchSegmentHybridModelOverride,
    run_segment_torch_bench_archive,
)
from .runtime_fusion import RuntimeFusion, StepMeta, StepResult
from .maca_serving_e2e import (
    MacaServingFullLayerE2EReport,
    run_maca_serving_full_layer_e2e_auto,
    run_torch_maca_serving_full_layer_e2e,
)
from .maca_serving_meta import (
    MACA_SERVING_DEFAULT_BLOCK_DIM,
    MACA_SERVING_SM_COUNT_C500,
    MACA_SERVING_WARP_SIZE,
    MacaServingRfSpec,
    attach_maca_serving_to_step_meta,
    inspect_maca_serving_meta,
    maca_serving_present,
    validate_maca_block_dim,
)
from .vllm_metax_plugin import (
    VllmMetaxMlpRfHookReport,
    VllmMetaxQwen2MlpRfHook,
    build_vllm_metax_qwen2_mlp_rf_hook,
    is_metax_torch,
    is_vllm_metax_available,
    require_vllm_metax,
    rf_step_meta_for_vllm_metax,
)
from .maca_exec import (
    YirageMacaServingMlpRunner,
    inspect_maca_serving_yirage_tier,
    is_yirage_maca_available,
    maca_superoptimize_kwargs,
    require_yirage_maca,
)
from .yirage_core_e2e import (
    YirageCoreFullLayerE2EReport,
    run_yirage_core_full_layer_e2e,
    run_yirage_core_full_layer_e2e_auto,
)
from .yirage_maca_e2e import (
    YirageMacaFullLayerE2EReport,
    run_yirage_maca_full_layer_e2e,
    run_yirage_maca_full_layer_e2e_auto,
)
from .yirage_maca_generation import (
    MCPYTORCH_BASELINE_NAME,
    YirageMacaGenerationBaselineArchive,
    YirageMacaGenerationBaselineSummary,
    YirageMacaGenerationReport,
    resolve_yirage_maca_generation_backend,
    run_yirage_maca_generation_auto,
    run_yirage_maca_generation_bench_archive,
    run_yirage_maca_generation_decode_loop,
    run_yirage_maca_generation_mcpytorch_baseline_archive,
)
from .sglang_metax_e2e import (
    SglangMetaxHybridE2EReport,
    SglangMetaxMlpRfE2EReport,
    SglangMetaxMultiLayerForkE2EReport,
    SglangMetaxForkE2EReport,
    run_sglang_metax_hybrid_full_e2e_auto,
    run_sglang_metax_mlp_rf_e2e_auto,
    run_sglang_metax_multilayer_fork_auto,
    run_sglang_metax_multilayer_fork_e2e,
    run_sglang_metax_qwen2_mlp_rf_e2e,
    run_sglang_metax_fork_e2e,
    run_torch_sglang_metax_hybrid_full_e2e,
    run_torch_sglang_metax_mlp_rf_e2e,
)
from .sglang_metax_plugin import (
    SglangMetaxBatchTorchMlpRfHook,
    SglangMetaxQwen2MlpRfHook,
    build_sglang_metax_batch_torch_mlp_rf_hook,
    build_sglang_metax_qwen2_mlp_rf_hook,
    is_sglang_metax_available,
    require_sglang_metax,
    rf_step_meta_for_sglang_metax,
)
from .yirage_exec import (
    YirageServingMlpRunner,
    bench_superoptimize_down_matmul,
    build_gate_up_seed_graph,
    build_mlp_down_seed_graph,
    is_yirage_core_available,
    require_yirage_core,
    superoptimize_down_matmul_cpu,
)

__all__ = [
    "FusionPlan",
    "FusionCapsule",
    "MlpFusionCapsule",
    "mlp_eager_numpy",
    "RuntimeFusion",
    "StepMeta",
    "StepResult",
    "QWEN2_MLP_HF_ATTACH",
    "EngineAttentionMeta",
    "EngineDecoderLayerStub",
    "EngineModelStub",
    "RuntimeFusionMlpLayerOverride",
    "LayerForwardResult",
    "build_layer_mlp_capsule",
    "capsule_name_for_layer",
    "build_split_mlp_runtime_fusion",
    "pipeline_meta_for_layer",
    "resolve_capsule_pipeline",
    "split_mlp_gate_up_name",
    "split_mlp_down_name",
    "split_mlp_pipeline_names",
    "MlpGateUpFusionCapsule",
    "MlpDownFusionCapsule",
    "build_layer_split_mlp_capsules",
    "split_mlp_parity_numpy",
    "split_mlp_matches_fused",
    "RuntimeFusionSplitMlpLayerOverride",
    "DecoderSegmentOverride",
    "SegmentHybridModelOverride",
    "SegmentForwardResult",
    "resolve_segment_layer_ids",
    "TorchSegmentHybridModelOverride",
    "TorchSegmentForwardResult",
    "run_segment_torch_bench_archive",
    "ServingBenchArchive",
    "ServingBenchArchiveRow",
    "is_sglang_available",
    "require_sglang",
    "rf_step_meta_from_forward_batch",
    "SGLANG_QWEN2_MLP_ATTACH",
    "SglangMlpWeightView",
    "SglangBatchTorchMlpRfHook",
    "SglangQwen2MlpRfHook",
    "build_sglang_batch_torch_mlp_rf_hook",
    "build_sglang_qwen2_mlp_rf_hook",
    "extract_sglang_qwen2_mlp_weights",
    "SglangForwardBatchSpec",
    "SglangMlpRfE2EReport",
    "SglangHybridE2EReport",
    "build_minimal_sglang_qwen2_decoder_layer",
    "run_torch_sglang_mlp_rf_e2e",
    "run_torch_sglang_hybrid_full_e2e",
    "run_sglang_qwen2_mlp_rf_e2e",
    "run_sglang_mlp_rf_e2e_auto",
    "is_vllm_available",
    "require_vllm",
    "require_vllm_cpu_serving",
    "TorchDecoderMlpRfHook",
    "build_torch_mlp_rf_hook",
    "VLLM_QWEN2_MLP_ATTACH",
    "VllmMlpWeightView",
    "VllmQwen2MlpRfHook",
    "build_vllm_qwen2_mlp_rf_hook",
    "extract_qwen2_mlp_weights",
    "VllmMlpRfE2EReport",
    "VllmHybridE2EReport",
    "build_minimal_vllm_qwen2_decoder_layer",
    "run_torch_vllm_mlp_rf_e2e",
    "run_torch_vllm_hybrid_full_e2e",
    "run_vllm_qwen2_mlp_rf_e2e",
    "DEFAULT_QWEN05B_MODEL",
    "HfQwen05bCpuE2EReport",
    "HfQwen2MlpLayerAdapter",
    "HfQwen2MlpRfHook",
    "build_hf_qwen_mlp_rf_hook",
    "is_transformers_available",
    "qwen2_forward_with_rf_mlp",
    "qwen2_decode_step_with_rf_mlp",
    "greedy_decode_with_rf_mlp",
    "resolve_hf_qwen_mlp_backend",
    "require_transformers",
    "run_hf_qwen05b_cpu_e2e",
    "run_vllm_mlp_rf_e2e_auto",
    "VllmPagedKvBatchSpec",
    "VllmPagedFullLayerE2EReport",
    "run_torch_vllm_paged_full_layer_e2e",
    "run_vllm_paged_full_layer_e2e_auto",
    "YirageCoreFullLayerE2EReport",
    "run_yirage_core_full_layer_e2e",
    "run_yirage_core_full_layer_e2e_auto",
    "YirageMacaFullLayerE2EReport",
    "run_yirage_maca_full_layer_e2e",
    "run_yirage_maca_full_layer_e2e_auto",
    "YirageMacaGenerationReport",
    "MCPYTORCH_BASELINE_NAME",
    "YirageMacaGenerationBaselineSummary",
    "YirageMacaGenerationBaselineArchive",
    "resolve_yirage_maca_generation_backend",
    "run_yirage_maca_generation_decode_loop",
    "run_yirage_maca_generation_bench_archive",
    "run_yirage_maca_generation_mcpytorch_baseline_archive",
    "run_yirage_maca_generation_auto",
    "YirageMacaServingMlpRunner",
    "SglangMetaxBatchTorchMlpRfHook",
    "SglangMetaxQwen2MlpRfHook",
    "SglangMetaxHybridE2EReport",
    "SglangMetaxMlpRfE2EReport",
    "SglangMetaxForkE2EReport",
    "SglangMetaxMultiLayerForkE2EReport",
    "build_sglang_metax_batch_torch_mlp_rf_hook",
    "build_sglang_metax_qwen2_mlp_rf_hook",
    "is_sglang_metax_available",
    "require_sglang_metax",
    "rf_step_meta_for_sglang_metax",
    "run_torch_sglang_metax_mlp_rf_e2e",
    "run_torch_sglang_metax_hybrid_full_e2e",
    "run_sglang_metax_hybrid_full_e2e_auto",
    "run_sglang_metax_qwen2_mlp_rf_e2e",
    "run_sglang_metax_fork_e2e",
    "run_sglang_metax_multilayer_fork_e2e",
    "run_sglang_metax_multilayer_fork_auto",
    "run_sglang_metax_mlp_rf_e2e_auto",
    "HybridModelOverride",
    "resolve_rf_mlp_layer_ids",
    "PagedKvMeta",
    "block_tables_to_paged_kv",
    "attach_paged_kv_to_step_meta",
    "last_page_len_from_seq",
    "RadixHitMeta",
    "parse_radix_hit_mask",
    "attach_radix_to_step_meta",
    "apply_radix_shrink",
    "build_sglang_rf_step_meta",
    "radix_hit_mask_from_sglang_extend_lens",
    "bootstrap_yirage_stub",
    "import_serving",
    "repo_root",
    "require_numpy",
    "run_serving_cpu_cert",
    "serving_cpu_cert_manifest",
    "CertReport",
    "CertStage",
    "SmWorkerQuota",
    "SmStepAllocation",
    "resolve_sm_worker_quota",
    "capsule_sm_cost",
    "assert_aux_coresidence",
    "DEFAULT_TOTAL_SMS",
    "DEFAULT_RESERVED_AUX_SMS",
    "DEFAULT_CAPSULE_SM_COST",
    "BACKEND_TORCH",
    "BACKEND_YIRAGE_CPU",
    "BACKEND_YIRAGE_MACA",
    "MACA_SERVING_WARP_SIZE",
    "MACA_SERVING_SM_COUNT_C500",
    "MACA_SERVING_DEFAULT_BLOCK_DIM",
    "MacaServingRfSpec",
    "attach_maca_serving_to_step_meta",
    "maca_serving_present",
    "inspect_maca_serving_meta",
    "validate_maca_block_dim",
    "MacaServingFullLayerE2EReport",
    "run_torch_maca_serving_full_layer_e2e",
    "run_maca_serving_full_layer_e2e_auto",
    "is_metax_torch",
    "is_vllm_metax_available",
    "require_vllm_metax",
    "VllmMetaxQwen2MlpRfHook",
    "build_vllm_metax_qwen2_mlp_rf_hook",
    "rf_step_meta_for_vllm_metax",
    "VllmMetaxMlpRfHookReport",
    "is_yirage_maca_available",
    "require_yirage_maca",
    "maca_superoptimize_kwargs",
    "inspect_maca_serving_yirage_tier",
    "is_maca_serving_backend",
    "default_serving_backend",
    "is_exec_backend",
    "is_yirage_backend",
    "is_yirage_core_available",
    "require_yirage_core",
    "YirageServingMlpRunner",
    "superoptimize_down_matmul_cpu",
    "bench_superoptimize_down_matmul",
    "build_gate_up_seed_graph",
    "build_mlp_down_seed_graph",
    "TorchEngineModel",
    "TorchDecoderLayer",
    "TorchAttentionMeta",
    "require_torch",
    "default_device",
    "mlp_torch",
    "bench_forward",
    "BenchResult",
    "to_torch",
    "to_numpy",
]
