#!/usr/bin/env python3
"""Generate README.pypi.md from README.md.

Extracts the Documentation and License sections from the main README and
assembles a concise, PyPI-friendly README.pypi.md.  The Installation, Quick
Start, Key Features, and Supported-Backends sections are maintained as a
curated template inside this script so the PyPI page stays readable even as
the main README grows.

Usage::

    python tools/generate_pypi_readme.py   # write README.pypi.md
    python tools/generate_pypi_readme.py --check  # exit 1 if out of date
    make readme-pypi
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
README_SRC = ROOT / "README.md"
README_OUT = ROOT / "README.pypi.md"

# ---------------------------------------------------------------------------
# Section extractors
# ---------------------------------------------------------------------------

_EMOJI_RE = re.compile(
    r"[\U0001F000-\U0001FFFF"
    r"\U00002700-\U000027BF"
    r"\U0001F900-\U0001F9FF"
    r"\u2705\u2714\u2728\u26A0\u2139"
    r"\U0001F300-\U0001F5FF"
    r"\u200d]+"
)


def _strip_emoji_heading(line: str) -> str:
    """Remove emoji from a Markdown heading line, collapse extra spaces."""
    if not line.startswith("#"):
        return line
    hashes, _, rest = line.partition(" ")
    rest = _EMOJI_RE.sub("", rest).strip()
    rest = re.sub(r"\s{2,}", " ", rest)
    return f"{hashes} {rest}"


def _extract_section(text: str, pattern: str, heading_level: int = 2) -> str:
    """Return the content of the first heading that matches *pattern*.

    Stops at the next heading of the same or higher level.
    Emoji are stripped from heading lines.
    """
    prefix = r"#{1," + str(heading_level) + r"}"
    search_re = re.compile(
        rf"^(#{{{heading_level}}})\s+[^\n]*{pattern}[^\n]*$",
        re.MULTILINE | re.IGNORECASE,
    )
    m = search_re.search(text)
    if not m:
        return ""

    start = m.start()
    stop_re = re.compile(rf"^{prefix} ", re.MULTILINE)
    end_m = stop_re.search(text, m.end())
    end = end_m.start() if end_m else len(text)

    section = text[start:end].rstrip()
    # Strip emoji from heading lines in the extracted block
    lines = [_strip_emoji_heading(ln) for ln in section.splitlines()]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Static (curated) template blocks
# ---------------------------------------------------------------------------

_STATIC_TEMPLATE = """\
<!-- This file is auto-generated by tools/generate_pypi_readme.py.
     Run `make readme-pypi` after updating README.md or the script template.
     DO NOT edit this file manually. -->

# YiRage

**Multi-Backend LLM Inference Optimization Engine**

YiRage is a high-performance tensor algebra superoptimizer that automatically
generates optimized GPU/NPU kernels for LLM inference across multiple hardware
backends.

## Supported Backends

| Backend | Hardware | Status |
|---------|----------|--------|
| CUDA | NVIDIA GPU | ✅ Production |
| MPS | Apple Silicon | ✅ Production |
| ROCm | AMD GPU | ✅ Beta |
| Ascend | Huawei NPU | ✅ Beta |
| TPU | Google TPU | 🔧 Alpha |
| MACA | MetaX GPU | 🔧 Alpha |
| XPU | Intel GPU | 🔧 Alpha |
| FPGA | Xilinx/Intel FPGA | 🔬 Experimental |
| CPU | Any | ✅ Production |

## Installation

YiRage is a **native extension**: `import yirage` requires a successful build
of the C++ runtime (`libyirage_runtime`) and the Cython module `yirage.core`.
There is no Python-only install path.

### From PyPI

Wheels (when published) ship the prebuilt native library.

```bash
pip install yirage
pip install yirage[cuda]         # NVIDIA CUDA
pip install yirage[rocm]         # AMD ROCm
pip install yirage[mps]          # Apple Silicon
pip install yirage[distributed]  # Ray distributed
pip install yirage[all]          # All optional Python dependencies
```

### From Source (Recommended for Full Backend Support)

```bash
git clone https://github.com/chenxingqiang/YiRage.git
cd YiRage

# Auto-detect hardware
pip install -e .

# Specify backend explicitly
YIRAGE_BACKEND=cuda pip install -e .    # NVIDIA GPU
YIRAGE_BACKEND=rocm pip install -e .    # AMD GPU
YIRAGE_BACKEND=mps pip install -e .     # Apple Silicon
YIRAGE_BACKEND=ascend pip install -e .  # Huawei NPU
YIRAGE_BACKEND=tpu pip install -e .     # Google TPU
YIRAGE_BACKEND=xpu pip install -e .     # Intel GPU
YIRAGE_BACKEND=maca pip install -e .    # MetaX GPU
YIRAGE_BACKEND=fpga pip install -e .    # FPGA
YIRAGE_BACKEND=cpu pip install -e .     # CPU backend (still builds full native runtime)

# Multiple backends
YIRAGE_BACKEND=cuda,cpu pip install -e .
```

## Quick Start

```python
import yirage as yr

# Check available backends
print(yr.get_available_backends())
# ['cuda', 'cpu'] or ['mps', 'cpu'] depending on hardware

# Create optimized kernel
graph = yr.new_kernel_graph()
X = graph.new_input(dims=(16, 1024), dtype=yr.float16)
W = graph.new_input(dims=(1024, 4096), dtype=yr.float16)
Y = graph.matmul(X, W)
graph.mark_output(Y)

# Search for optimal implementation
optimized = yr.search(graph, backend='cuda')
```

## Key Features

- **Multi-Backend Support**: Single codebase for NVIDIA, AMD, Apple, Google, Huawei, Intel, MetaX hardware
- **12 Hardware Backends**: CUDA, ROCm, MPS, Ascend, TPU, XPU, MACA, FPGA, CPU, and more
- **Automatic Optimization**: Finds optimal kernel implementations via search
- **LLM-Focused**: Optimized for attention, FFN, and other LLM operators
- **Production Ready**: Battle-tested in production inference systems

"""

# ---------------------------------------------------------------------------
# Main assembly
# ---------------------------------------------------------------------------


def build_pypi_readme(src_text: str) -> str:
    """Assemble README.pypi.md content from the static template and extracted sections."""
    # Extract Documentation and License from the main README
    docs_section = _extract_section(src_text, r"Documentation", heading_level=2)
    license_section = _extract_section(src_text, r"License", heading_level=2)

    parts = [_STATIC_TEMPLATE.rstrip()]

    if docs_section:
        parts.append("")
        parts.append(docs_section)

    if license_section:
        parts.append("")
        parts.append(license_section)

    return "\n".join(parts) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit with code 1 if README.pypi.md would change (useful in CI).",
    )
    args = parser.parse_args()

    src_text = README_SRC.read_text(encoding="utf-8")
    new_content = build_pypi_readme(src_text)

    if args.check:
        if README_OUT.exists():
            current = README_OUT.read_text(encoding="utf-8")
            if current == new_content:
                print("README.pypi.md is up to date.")
                sys.exit(0)
        print(
            "README.pypi.md is out of date. Run `make readme-pypi` to regenerate.",
            file=sys.stderr,
        )
        sys.exit(1)

    README_OUT.write_text(new_content, encoding="utf-8")
    print(f"Written {README_OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
